const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const carousel = require('../static/js/setup_carousel.js');
const htmlSafety = require('../static/js/html_safety.js');

assert.equal(carousel.wrapIndex(-1, 6), 5);
assert.equal(carousel.wrapIndex(6, 6), 0);
assert.equal(carousel.normalizeTrackIndex(5, 6), 11);
assert.equal(carousel.normalizeTrackIndex(12, 6), 6);

let trackIndex = 6;
let logicalOffset = 0;
for (let index = 0; index < 1000; index += 1) {
    const next = carousel.nextState(trackIndex, logicalOffset, 1, 6);
    trackIndex = carousel.normalizeTrackIndex(next.destinationIndex, 6);
    logicalOffset = next.logicalOffset;
}
assert.equal(logicalOffset, 4);
assert.ok(trackIndex >= 6 && trackIndex < 12);

for (let index = 0; index < 2000; index += 1) {
    const next = carousel.nextState(trackIndex, logicalOffset, -1, 6);
    trackIndex = carousel.normalizeTrackIndex(next.destinationIndex, 6);
    logicalOffset = next.logicalOffset;
}
assert.equal(logicalOffset, 2);
assert.ok(trackIndex >= 6 && trackIndex < 12);

assert.equal(carousel.shouldRemainColored(false, false), false);
assert.equal(carousel.shouldRemainColored(true, false), true);
assert.equal(carousel.shouldRemainColored(false, true), true);

const hostileImport = "<img src=x onerror='globalThis.pwned=true'>${globalThis.pwned=true}'\\";
const escapedImport = htmlSafety.escapeHTML(hostileImport);
assert.ok(!/[<>"']/.test(escapedImport));
assert.ok(escapedImport.includes('&lt;img'));
assert.ok(escapedImport.includes('&#39;'));

const appSource = fs.readFileSync(path.join(__dirname, '..', 'static', 'js', 'app.js'), 'utf8');
const bootSource = fs.readFileSync(path.join(__dirname, '..', 'static', 'js', 'boot.js'), 'utf8');
const studioCss = fs.readFileSync(path.join(__dirname, '..', 'static', 'css', 'views', 'studio-pages.css'), 'utf8');
const modelManagerCss = fs.readFileSync(path.join(__dirname, '..', 'static', 'css', 'views', 'model-manager.css'), 'utf8');
assert.ok(!appSource.includes('<div class="sr-q-text">${p.q}</div>'));
assert.ok(!appSource.includes('<div class="sr-a-text">${p.a}</div>'));
assert.ok(!appSource.includes('p.q.replace(/`/g'));
assert.ok(appSource.includes("fetch('/api/system/status')"));
assert.ok(appSource.includes("LOCAL AI · SETUP NEEDED"));
assert.ok(appSource.includes('role="status" aria-live="polite"'));
assert.ok(appSource.includes('aria-label="Local AI status: checking"'));
assert.ok(appSource.includes('function refreshHeroSessionStrip()'));
assert.ok(appSource.includes('id="hero-last-strip" aria-live="polite"'));
assert.ok(appSource.includes('<strong>No sessions yet</strong>'));
assert.ok(!appSource.includes('<strong>Product Manager</strong>'));
assert.ok(!appSource.includes('<span class="hero-last-score">84 <small>score</small></span>'));
assert.ok(appSource.includes('await durableStorage.ready'));
assert.ok(appSource.includes("'models': renderModelManager"));
assert.ok(appSource.includes("if (!data.model_setup_completed || !data.selected_ready)"));
assert.ok(appSource.includes("fetch('/api/models/select'"));
assert.ok(appSource.includes("fetch('/api/setup/pull'"));
assert.ok(appSource.includes("const downloading = pulling && !choice.installed;"));
assert.ok(appSource.includes('class="mm-state-panel mm-download-stage"'));
assert.ok(appSource.includes('Download paused'));
assert.ok(appSource.includes('Your coach is ready'));
assert.equal((appSource.match(/id: '(?:qwen2\.5:7b|qwen3\.5:4b|granite3\.3:8b|phi4-mini-reasoning:3\.8b)'/g) || []).length, 4);
assert.ok(appSource.includes('Pick one model to begin. You can add or switch models later.'));
assert.ok(appSource.includes("window.chrome.webview.postMessage({ type: 'open-ollama' })"));
assert.ok(appSource.includes("window.chrome.webview.postMessage({ type: 'download-ollama' })"));
assert.ok(appSource.includes("const downloadUrl = 'https://ollama.com/download/windows'"));
assert.ok(appSource.includes('class="mm-download-ollama"'));
assert.ok(appSource.includes('downloadController?.abort()'));
assert.ok(appSource.includes("error?.name === 'AbortError'"));
assert.ok(appSource.includes('Ollama kept the completed files'));
assert.ok(appSource.includes('/static/assets/setup/ollama-llama.png'));
assert.ok(appSource.includes("const OPENING_VARIANT = 'dark';"));
assert.ok(appSource.includes('mm-opening mm-opening--${OPENING_VARIANT}'));
assert.ok(appSource.includes('const openingRevealMs = 1800;'));
assert.ok(appSource.includes('const openingHoldMs = 1400;'));
assert.ok(appSource.includes('const openingTransitionMs = 3000;'));
assert.ok(appSource.includes('const reducedMotionFadeMs = 120;'));
assert.ok(appSource.includes("opening.classList.add('is-entering-app')"));
assert.ok(appSource.includes("mainContent.setAttribute('inert', '')"));
assert.ok(appSource.includes("document.body.classList.remove('ic-booting')"));
assert.equal((appSource.match(/id="mm-opening-lockup-geometry"/g) || []).length, 1);
assert.equal((appSource.match(/class="mm-opening-visible-lockup"/g) || []).length, 1);
assert.equal((appSource.match(/class="mm-opening-visible-mark-details"/g) || []).length, 1);
assert.equal((appSource.match(/class="mm-opening-mask-reference"/g) || []).length, 1);
assert.ok(appSource.includes('class="mm-opening-stage"'));
assert.ok(appSource.includes('mask id="mm-opening-surface-mask"'));
assert.ok(appSource.includes('<use class="mm-opening-mask-reference" href="#mm-opening-lockup-geometry"></use>'));
assert.ok(!appSource.includes('mm-opening-lockup-alpha'));
assert.ok(!appSource.includes('mm-opening-focus-aperture'));
assert.ok(!appSource.includes('mm-opening-tunnel-solid'));
assert.ok(!appSource.includes('mm-opening-tunnel-cutout'));
assert.ok(!appSource.includes('mm-opening-focus-letter'));
assert.ok(appSource.includes('const scales = [1, 1.15, 2.8, 8, 30, finalScale];'));
assert.ok(appSource.includes("opening.dataset.openingPhase = 'tunnel';"));
assert.ok(appSource.includes('await waitForDestinationPaint();'));
assert.ok(appSource.includes('wait(750)'));
assert.ok(appSource.includes('visibleTunnel.finished.catch'));
assert.ok(appSource.includes('transparentTunnel.finished.catch'));
assert.ok(appSource.includes('surfaceRelease.finished.catch'));
assert.ok(appSource.includes("{ offset: 1, opacity: 0 }"));
assert.match(appSource, /await nextFrame\(\);\s+finishOpening\(\);/);
assert.ok(appSource.includes('showCoachPicker = false;'));
assert.ok(modelManagerCss.includes('.mm-opening-visible-lockup'));
assert.ok(modelManagerCss.includes('.mm-opening-mask-reference'));
assert.ok(modelManagerCss.includes('.mm-opening-geometry-mark-fill'));
assert.ok(!modelManagerCss.includes('mix-blend-mode: screen'));
assert.ok(modelManagerCss.includes('.mm-opening--dark .mm-opening-scrim { display: none; }'));
assert.ok(modelManagerCss.includes('.mm-opening--ivory .mm-opening-tunnel-surface { display: none; }'));
assert.ok(!modelManagerCss.includes('@keyframes mm-letter-tunnel-cutout'));
assert.ok(!modelManagerCss.includes('@keyframes mm-solid-letter-tunnel'));
assert.ok(!modelManagerCss.includes('@keyframes mm-retire-html-lockup'));
assert.ok(!modelManagerCss.includes('mm-opening-focus-aperture'));
assert.ok(appSource.includes("filter:invert(1) hue-rotate(180deg) saturate(.9) brightness(1.03)"));
assert.ok(appSource.includes("linear-gradient(145deg,#b84a30 0%,#a63a25 54%,#8f3021 100%)"));
assert.ok(!appSource.includes('@keyframes btnShimmer'));
assert.ok(appSource.includes("if (!document.documentElement.classList.contains('ic-opening'))"));
assert.ok(appSource.includes("setupSelectionCircle('su-mod-circle')"));
assert.ok(!appSource.includes("setupSelectionCircle('su-char-circle')"));
assert.ok(appSource.includes("setupSelectionCircle('su-option-circle')"));
assert.ok(!appSource.includes('su-char-ink'));
assert.ok(!appSource.includes('su-option-check'));
assert.ok(!appSource.toLowerCase().includes('press any key to skip'));
assert.ok(appSource.includes('Starting Interview Chameleon'));
assert.ok(appSource.includes("label: 'AI Models'"));
assert.ok(appSource.includes("persistLocalValue('qb_favorites'"));
assert.ok(bootSource.includes("question_favorites: ['qb_favorites', true]"));
assert.ok(bootSource.includes("minigame_runs: ['mg_runs_v2', true]"));
assert.ok(bootSource.includes("mg_salary_best: 'salary'"));
assert.ok(bootSource.includes('window.InterviewChameleonStorage = { ready, setItem, flush }'));
assert.ok(appSource.includes('Promise.allSettled([checkpoint, preferences])'));
assert.ok(studioCss.includes('content: attr(data-runtime-label)'));
assert.ok(!studioCss.includes("content: 'LOCAL AI · READY'"));
assert.ok(studioCss.includes("filter: invert(1) hue-rotate(180deg) saturate(.9) brightness(1.03)"));
assert.ok(studioCss.includes('@keyframes su-brand-mark-pulse'));
assert.ok(studioCss.includes(".su-condition-options .su-tgl[class*='on-'].is-drawing"));
assert.ok(studioCss.includes('width: min(72%, 248px);'));
assert.ok(studioCss.includes('.su-wrap .su-focus-note:focus-visible'));
assert.ok(studioCss.includes('box-shadow: inset 0 -3px 0 var(--studio-green) !important;'));
assert.ok(studioCss.includes('.su-wrap .su-sw { border-radius: 999px !important; }'));
assert.ok(appSource.includes("navigate('models', { returnTo: 'setup' })"));
assert.ok(appSource.includes("navigate('setup', { resumeDraft: true })"));
assert.ok(appSource.includes('const restoredDraft = options.resumeDraft && setupDraft ? setupDraft : null;'));

console.log('frontend state tests passed');
